#pragma once

#define PROCESS_SUSPECT_FLAGS (PROCESS_VM_WRITE | PROCESS_CREATE_THREAD | PROCESS_SET_INFORMATION | PROCESS_SET_LIMITED_INFORMATION |PROCESS_DUP_HANDLE | PROCESS_SET_QUOTA | PROCESS_SUSPEND_RESUME | PROCESS_VM_OPERATION)
#define THREAD_SUSPECT_FLAGS  (THREAD_SET_INFORMATION | THREAD_SET_LIMITED_INFORMATION | THREAD_SET_CONTEXT | THREAD_SUSPEND_RESUME)

void c_anti_hack::scan_process() {


}
